name: terraform-apply

on:
  workflow_dispatch:
    inputs:
      allow_destructive:
        description: "Allow delete/replace actions in Terraform plan"
        required: true
        default: "false"

concurrency:
  group: bootstrap-terraform
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "1"
      TF_S3_ENDPOINT: ${{ secrets.TF_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: garage
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      TF_BOOTSTRAP_TFVARS_JSON: ${{ secrets.TF_BOOTSTRAP_TFVARS_JSON }}
      ALLOW_DESTRUCTIVE: ${{ inputs.allow_destructive }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install terraform + kubectl + jq (if missing)
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v apt-get >/dev/null 2>&1; then
            echo "apt-get not found; cannot install dependencies on this runner image." >&2
            exit 2
          fi
          if [[ "$(id -u)" != "0" ]]; then
            echo "Runner is not root and sudo is unavailable; cannot apt-get install dependencies." >&2
            exit 2
          fi
          apt-get update
          apt-get install -y ca-certificates curl jq unzip
          if ! command -v terraform >/dev/null 2>&1; then
            curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
            unzip -o /tmp/terraform.zip -d /usr/local/bin
          fi
          if ! command -v kubectl >/dev/null 2>&1; then
            curl -fsSL -o /tmp/kubectl https://dl.k8s.io/release/v1.34.0/bin/linux/amd64/kubectl
            install -m 0755 /tmp/kubectl /usr/local/bin/kubectl
          fi
          terraform version
          kubectl version --client=true --output=yaml | head -n 20

      - name: "Guard: required secrets"
        shell: bash
        run: |
          set -euo pipefail
          : "${TF_S3_ENDPOINT:?Set Forgejo secret TF_S3_ENDPOINT (e.g. http://platform-garage.garage.svc:3900)}"
          : "${AWS_ACCESS_KEY_ID:?Set Forgejo secret AWS_ACCESS_KEY_ID (Garage S3 key id)}"
          : "${AWS_SECRET_ACCESS_KEY:?Set Forgejo secret AWS_SECRET_ACCESS_KEY (Garage S3 secret key)}"
          : "${TF_VAR_proxmox_api_token:?Set Forgejo secret PROXMOX_VE_API_TOKEN (Proxmox API token secret)}"
          if [[ "${TF_VAR_proxmox_api_token}" != *"@"*"!"*"="* ]]; then
            echo "PROXMOX_VE_API_TOKEN looks malformed. Expected format: user@realm!tokenid=secret (example: root@pam!terraform=xxxxxxxx)." >&2
            exit 2
          fi

      - name: Export optional platform repo auth TF vars
        shell: bash
        env:
          PLATFORM_REPO_USERNAME: ${{ secrets.TF_VAR_platform_repo_username }}
          PLATFORM_REPO_PASSWORD: ${{ secrets.TF_VAR_platform_repo_password }}
        run: |
          set -euo pipefail
          if [[ -z "${PLATFORM_REPO_USERNAME:-}" && -z "${PLATFORM_REPO_PASSWORD:-}" ]]; then
            echo "No platform repo auth secrets set; leaving platform_repo_username/password unset (null)."
            exit 0
          fi
          : "${PLATFORM_REPO_USERNAME:?Set TF_VAR_platform_repo_username (or unset both username+password)}"
          : "${PLATFORM_REPO_PASSWORD:?Set TF_VAR_platform_repo_password (or unset both username+password)}"
          {
            echo "TF_VAR_platform_repo_username=${PLATFORM_REPO_USERNAME}"
            echo "TF_VAR_platform_repo_password=${PLATFORM_REPO_PASSWORD}"
          } >> "${GITHUB_ENV}"

      - name: Write CI tfvars (optional)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -f terraform/cluster.auto.tfvars.json || -f terraform/cluster.auto.tfvars || -f terraform/terraform.tfvars || -f terraform/terraform.tfvars.json ]]; then
            echo "Found repo-provided tfvars; using in-repo config."
            exit 0
          fi
          if [[ -z "${TF_BOOTSTRAP_TFVARS_JSON:-}" ]]; then
            echo "Missing config: add terraform/cluster.auto.tfvars(.json) to repo OR set TF_BOOTSTRAP_TFVARS_JSON secret." >&2
            exit 2
          fi
          umask 077
          echo "${TF_BOOTSTRAP_TFVARS_JSON}" > terraform/ci.auto.tfvars.json

      - name: Terraform init (Garage backend)
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform init -input=false \
            -backend-config="endpoint=${TF_S3_ENDPOINT}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="force_path_style=true" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_requesting_account_id=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="skip_region_validation=true"

      - name: Terraform plan (save)
        shell: bash
        run: |
          set -euo pipefail
          # Avoid printing full plan to logs (may contain sensitive values from prior state).
          terraform -chdir=terraform plan -input=false -no-color -out=plan.tfplan >/dev/null

      - name: "Guard: destructive plan requires allow_destructive=true"
        if: ${{ env.ALLOW_DESTRUCTIVE != 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform show -json plan.tfplan \
            | jq -e '
                [.resource_changes[]?.change.actions] as $a
                | any($a[]; index("delete") != null)
                  or any($a[]; (. == ["create","delete"]) or (. == ["delete","create"]))
              ' >/dev/null \
            && { echo "Plan includes delete/replace; re-run workflow with allow_destructive=true." >&2; exit 3; } \
            || echo "Plan is non-destructive; proceeding."

      - name: Terraform apply (from saved plan)
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform apply -input=false -auto-approve -no-color plan.tfplan
