name: terraform

on:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: bootstrap-terraform
  cancel-in-progress: false

jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install terraform (if missing)
        shell: bash
        run: |
          set -euo pipefail
          if command -v terraform >/dev/null 2>&1; then
            terraform version
            exit 0
          fi
          if ! command -v apt-get >/dev/null 2>&1; then
            echo "apt-get not found; cannot auto-install terraform on this runner image." >&2
            exit 2
          fi
          if [[ "$(id -u)" != "0" ]]; then
            echo "Runner is not root and sudo is unavailable; cannot apt-get install terraform prerequisites." >&2
            exit 2
          fi
          apt-get update
          apt-get install -y ca-certificates curl unzip
          curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
          unzip -o /tmp/terraform.zip -d /usr/local/bin
          terraform version

      - name: Terraform fmt
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform fmt -check -recursive

      - name: Terraform init (backend/local)
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform init -input=false -backend=false

      - name: Terraform validate
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform validate

  apply_main_non_destructive:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [fmt_validate]
    env:
      TF_IN_AUTOMATION: "1"
      TF_S3_ENDPOINT: ${{ secrets.TF_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: garage
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      # Option A (recommended): commit a non-secret tfvars file in git (see README).
      # Option B: provide all variables as a single JSON tfvars blob.
      TF_BOOTSTRAP_TFVARS_JSON: ${{ secrets.TF_BOOTSTRAP_TFVARS_JSON }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install terraform + kubectl + jq (if missing)
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v apt-get >/dev/null 2>&1; then
            echo "apt-get not found; cannot install dependencies on this runner image." >&2
            exit 2
          fi
          if [[ "$(id -u)" != "0" ]]; then
            echo "Runner is not root and sudo is unavailable; cannot apt-get install dependencies." >&2
            exit 2
          fi
          apt-get update
          apt-get install -y ca-certificates curl jq unzip
          if ! command -v terraform >/dev/null 2>&1; then
            curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
            unzip -o /tmp/terraform.zip -d /usr/local/bin
          fi
          if ! command -v kubectl >/dev/null 2>&1; then
            curl -fsSL -o /tmp/kubectl https://dl.k8s.io/release/v1.34.0/bin/linux/amd64/kubectl
            install -m 0755 /tmp/kubectl /usr/local/bin/kubectl
          fi
          terraform version
          kubectl version --client=true --output=yaml | head -n 20

      - name: "Guard: required secrets"
        shell: bash
        run: |
          set -euo pipefail
          : "${TF_S3_ENDPOINT:?Set Forgejo secret TF_S3_ENDPOINT (e.g. http://platform-garage.garage.svc:3900)}"
          : "${AWS_ACCESS_KEY_ID:?Set Forgejo secret AWS_ACCESS_KEY_ID (Garage S3 key id)}"
          : "${AWS_SECRET_ACCESS_KEY:?Set Forgejo secret AWS_SECRET_ACCESS_KEY (Garage S3 secret key)}"
          : "${TF_VAR_proxmox_api_token:?Set Forgejo secret PROXMOX_VE_API_TOKEN (Proxmox API token secret)}"

      - name: Export optional platform repo auth TF vars
        shell: bash
        env:
          PLATFORM_REPO_USERNAME: ${{ secrets.TF_VAR_platform_repo_username }}
          PLATFORM_REPO_PASSWORD: ${{ secrets.TF_VAR_platform_repo_password }}
        run: |
          set -euo pipefail
          if [[ -z "${PLATFORM_REPO_USERNAME:-}" && -z "${PLATFORM_REPO_PASSWORD:-}" ]]; then
            echo "No platform repo auth secrets set; leaving platform_repo_username/password unset (null)."
            exit 0
          fi
          : "${PLATFORM_REPO_USERNAME:?Set TF_VAR_platform_repo_username (or unset both username+password)}"
          : "${PLATFORM_REPO_PASSWORD:?Set TF_VAR_platform_repo_password (or unset both username+password)}"
          {
            echo "TF_VAR_platform_repo_username=${PLATFORM_REPO_USERNAME}"
            echo "TF_VAR_platform_repo_password=${PLATFORM_REPO_PASSWORD}"
          } >> "${GITHUB_ENV}"

      - name: Write CI tfvars (optional)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -f terraform/cluster.auto.tfvars.json || -f terraform/cluster.auto.tfvars || -f terraform/terraform.tfvars || -f terraform/terraform.tfvars.json ]]; then
            echo "Found repo-provided tfvars; using in-repo config."
            exit 0
          fi
          if [[ -z "${TF_BOOTSTRAP_TFVARS_JSON:-}" ]]; then
            echo "Missing config: add terraform/cluster.auto.tfvars(.json) to repo OR set TF_BOOTSTRAP_TFVARS_JSON secret." >&2
            exit 2
          fi
          umask 077
          echo "${TF_BOOTSTRAP_TFVARS_JSON}" > terraform/ci.auto.tfvars.json

      - name: Terraform init (Garage backend)
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform init -input=false \
            -backend-config="endpoint=${TF_S3_ENDPOINT}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="force_path_style=true" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_requesting_account_id=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="skip_region_validation=true"

      - name: Terraform plan (save)
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform plan -input=false -no-color -out=plan.tfplan

      - name: "Guard: block destructive changes by default"
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform show -json plan.tfplan \
            | jq -e '
                [.resource_changes[]?.change.actions] as $a
                | any($a[]; index("delete") != null)
                  or any($a[]; (. == ["create","delete"]) or (. == ["delete","create"]))
              ' >/dev/null \
            && { echo "Refusing to auto-apply: plan includes delete/replace actions. Use the manual apply workflow." >&2; exit 3; } \
            || echo "Plan is non-destructive (no delete/replace); proceeding."

      - name: Terraform apply (from saved plan)
        shell: bash
        run: |
          set -euo pipefail
          terraform -chdir=terraform apply -input=false -auto-approve -no-color plan.tfplan
